export const data = [
  "Some interesting questions people ask ChatGPT: What is the meaning of life?",
  "Some interesting questions people ask ChatGPT: What would happen if the Earth stopped spinning?",
  "Some interesting questions people ask ChatGPT: Can you write a short story about a robot who gains consciousness?",
  "Some interesting questions people ask ChatGPT: What is the most complex organism on Earth?",
  "Some interesting questions people ask ChatGPT: What is the largest known prime number?",
  "Some interesting questions people ask ChatGPT: What are some of the most important scientific discoveries in history?",
  "Some interesting questions people ask ChatGPT: Can you generate a recipe for a three course meal?",
  "Some interesting questions people ask ChatGPT: What are some interesting facts about black holes?",
  "Some interesting questions people ask ChatGPT: Can you write a poem about love and loss?",
  "Some interesting questions people ask ChatGPT: What is the history of the internet?",
  "Some interesting questions people ask ChatGPT: What is the likelihood of a zombies outbreak happening?",
  "Some interesting questions people ask ChatGPT: Can you generate a script for a short film?",
  "Some interesting questions people ask ChatGPT: What are the most common misconceptions about AI?",
  "Some interesting questions people ask ChatGPT: What is the impact of climate change on the ocean?",
  "Some interesting questions people ask ChatGPT: What are some of the most interesting unsolved mysteries in science?",
  "Some interesting questions people ask ChatGPT: Can you generate a design for a small garden?",
  "Some interesting questions people ask ChatGPT: What are the most significant events in human history?",
  "Some interesting questions people ask ChatGPT: What are the best ways to reduce stress?",
  "Some interesting questions people ask ChatGPT: Can you generate a song about love and heartbreak?",
  "Some interesting questions people ask ChatGPT: What are the most significant technological advancements in the last century?",
  "Some interesting questions people ask ChatGPT: What are the best ways to improve memory?",
  "Some interesting questions people ask ChatGPT: Can you explain the concept of dark matter?",
  "Some interesting questions people ask ChatGPT: What are the most common causes of anxiety?",
  "Some interesting questions people ask ChatGPT: What are the most significant discoveries in neuroscience?",
  "Some interesting questions people ask ChatGPT: Can you generate a recipe for a healthy meal?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of the internet?",
  "Some interesting questions people ask ChatGPT: What are the most effective ways to combat cyberbullying?",
  "Some interesting questions people ask ChatGPT: Can you generate a workout plan for building muscle?",
  "Some interesting questions people ask ChatGPT: What are the most significant technological advancements in the field of medicine?",
  "Some interesting questions people ask ChatGPT: Can you write a short story about a robot uprising?",
  "Some interesting questions people ask ChatGPT: Can you generate a script for a sci-fi movie?",
  "Some interesting questions people ask ChatGPT: What are the most interesting unsolved mysteries in history?",
  "Some interesting questions people ask ChatGPT: Can you generate a design for a small apartment?",
  "Some interesting questions people ask ChatGPT: What are the most significant events in the history of art?",
  "Some interesting questions people ask ChatGPT: What are the best ways to learn to code?",
  "Some interesting questions people ask ChatGPT: Can you generate a song about hope and perseverance?",
  "Some interesting questions people ask ChatGPT: What are the most significant technological advancements in the field of transportation?",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about blockchain technology?",
  "Some interesting questions people ask ChatGPT: How can I improve my negotiation skills?",
  "Some interesting questions people ask ChatGPT: Can you generate a haiku about the city?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of literature?",
  "Some interesting questions people ask ChatGPT: Can you write a short story about the future of humanity?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in artificial intelligence?",
  "Some interesting questions people ask ChatGPT: Can you generate an algorithm to solve a specific problem?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of space exploration?",
  "Some interesting questions people ask ChatGPT: Can you provide an explanation of quantum mechanics?",
  "Some interesting questions people ask ChatGPT: What are the most common misconceptions about the human brain?",
  "Some interesting questions people ask ChatGPT: Can you give me a summary of the latest news about a specific topic?",
  "Some interesting questions people ask ChatGPT: What are the most interesting unsolved problems in mathematics?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the top books in a specific genre?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of psychology?",
  "Some interesting questions people ask ChatGPT: Can you write a persuasive essay on a specific topic?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in renewable energy?",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific scientific concept?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of economics?",
  "Some interesting questions people ask ChatGPT: Can you write a short story about a person traveling through time?",
  "Some interesting questions people ask ChatGPT: Can you generate a script for a comedy movie?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of medicine?",
  "Some interesting questions people ask ChatGPT: Can you write a poem about love?",
  "Some interesting questions people ask ChatGPT: What are the most common misconceptions about climate change?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best exercises for a specific muscle group?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in biotechnology?",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific historical event?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of politics?",
  "Some interesting questions people ask ChatGPT: Can you write a business plan for a startup?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of robotics?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best tourist attractions in a specific city?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of philosophy?",
  "Some interesting questions people ask ChatGPT: Can you generate a recipe for a dish?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of technology?",
  "Some interesting questions people ask ChatGPT: Can you write a song about a specific topic?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in Artificial Intelligence?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best colleges for a specific major?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of the internet?",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific scientific phenomenon?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of transportation?",
  "Some interesting questions people ask ChatGPT: Can you write a script for a drama movie?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of nanotechnology?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best hikes in a specific national park?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of education?",
  "Some interesting questions people ask ChatGPT: Can you write a script for a video game?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of space exploration?",
  "Some interesting questions people ask ChatGPT: Can you write a short story about a specific topic?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in renewable energy?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best museums in a specific city?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of economics?",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific mathematical concept?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of psychology?",
  "Some interesting questions people ask ChatGPT: Can you write a script for an animated movie?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of biochemistry?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best beaches in a specific country?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of sociology?",
  "Some interesting questions people ask ChatGPT: Can you write a script for a TV series?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of medicine?",
  "Some interesting questions people ask ChatGPT: Can you write a poem about a specific topic?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of robotics?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best restaurants in a specific area?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of architecture?",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific geological phenomenon?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of environmental science?",
  "Some interesting questions people ask ChatGPT: Can you write a script for a stand-up comedy show?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of artificial intelligence in healthcare?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best historical landmarks in a specific city?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of political science?",
  "Some interesting questions people ask ChatGPT: Can you write a script for a movie?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of technology?",
  "Some interesting questions people ask ChatGPT: Can you write a song about a specific topic?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of quantum computing?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best hotels in a specific location?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of psychology?",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific concept in physics?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of computer science?",
  "Some interesting questions people ask ChatGPT: Can you write a script for a web series?",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of renewable energy?",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best parks in a specific city?",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of economics?",
];
