export const data = [
  "Some interesting questions people ask ChatGPT: What is the meaning of life? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What would happen if the Earth stopped spinning? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a short story about a robot who gains consciousness? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What is the most complex organism on Earth? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What is the largest known prime number? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are some of the most important scientific discoveries in history? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a recipe for a three course meal? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are some interesting facts about black holes? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a poem about love and loss? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What is the history of the internet? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What is the likelihood of a zombies outbreak happening? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a script for a short film? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most common misconceptions about AI? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What is the impact of climate change on the ocean? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are some of the most interesting unsolved mysteries in science? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a design for a small garden? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most significant events in human history? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the best ways to reduce stress? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a song about love and heartbreak? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most significant technological advancements in the last century? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the best ways to improve memory? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you explain the concept of dark matter? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most common causes of anxiety? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most significant discoveries in neuroscience? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a recipe for a healthy meal? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of the internet? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most effective ways to combat cyberbullying? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a workout plan for building muscle? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most significant technological advancements in the field of medicine? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a short story about a robot uprising? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a script for a sci-fi movie? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most interesting unsolved mysteries in history? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a design for a small apartment? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most significant events in the history of art? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the best ways to learn to code? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a song about hope and perseverance? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most significant technological advancements in the field of transportation? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about blockchain technology? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: How can I improve my negotiation skills? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a haiku about the city? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of literature? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a short story about the future of humanity? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in artificial intelligence? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate an algorithm to solve a specific problem? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of space exploration? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you provide an explanation of quantum mechanics? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most common misconceptions about the human brain? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you give me a summary of the latest news about a specific topic? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most interesting unsolved problems in mathematics? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the top books in a specific genre? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of psychology? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a persuasive essay on a specific topic? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in renewable energy? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific scientific concept? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of economics? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a short story about a person traveling through time? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a script for a comedy movie? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of medicine? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a poem about love? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most common misconceptions about climate change? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best exercises for a specific muscle group? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in biotechnology? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific historical event? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of politics? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a business plan for a startup? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of robotics? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best tourist attractions in a specific city? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of philosophy? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a recipe for a dish? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of technology? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a song about a specific topic? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in Artificial Intelligence? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best colleges for a specific major? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of the internet? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific scientific phenomenon? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of transportation? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a script for a drama movie? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of nanotechnology? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best hikes in a specific national park? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of education? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a script for a video game? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of space exploration? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a short story about a specific topic? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in renewable energy? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best museums in a specific city? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of economics? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific mathematical concept? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of psychology? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a script for an animated movie? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of biochemistry? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best beaches in a specific country? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of sociology? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a script for a TV series? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of medicine? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a poem about a specific topic? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of robotics? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best restaurants in a specific area? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of architecture? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific geological phenomenon? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of environmental science? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a script for a stand-up comedy show? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of artificial intelligence in healthcare? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best historical landmarks in a specific city? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of political science? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a script for a movie? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of technology? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a song about a specific topic? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of quantum computing? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best hotels in a specific location? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of psychology? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you provide a detailed explanation about a specific concept in physics? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of computer science? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you write a script for a web series? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important developments in the field of renewable energy? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: Can you generate a list of the best parks in a specific city? #ChatGPT #ChatGPTQuestions #Openai",
  "Some interesting questions people ask ChatGPT: What are the most important events in the history of economics? #ChatGPT #ChatGPTQuestions #Openai",
];
