version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  Tweet:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  Tweet-workflow:
    jobs:
      - Tweet
