version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  Tweet:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          install-node: true
          node-version: "18.00"
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Run tests
          command: npm test
          env:
            ACCESS_TOKEN: $ACCESS_TOKEN
            ACCESS_TOKEN_SECRET: $ACCESS_TOKEN_SECRET
            API_KEY: $API_KEY
            API_SECRET: $API_SECRET

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  Tweet-workflow:
    jobs:
      - Tweet
