name: Node.js CI

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 22 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm start
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN}}
        API_KEY: ${{secrets.ACCESS_TOKEN}}
        API_SECRET: ${{secrets.ACCESS_TOKEN}}
